# fly.toml app configuration file generated for bbauth on 2026-04-09T14:10:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bbauth'
primary_region = 'cdg'

[build]

[[mounts]]
  source      = "bbauth_data"
  destination = "/data"


[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
